### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by ghost** [kost/js-zynpass#1]
Hey, I'm sorry for creating this, but I could think of no other way to contact you! I have some questions on how to use ZynPass, what do I input for "custom magic number". And how exactly do I use this?

**Comment by kost** [comment]
Custom magic number is only if your vendor changed the magic. Usually, you can just use already generated and usually used numbers. Usually it is 10F0A563 or A11F5AC6. Check 
https://github.com/kost/js-zynpass/blob/master/index.js

You can check at web app here:
http://kost.github.io/util/zynpass/
